[package]
name = "memcached_codec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.2"
bytes = "1.4.0"
thiserror = "1.0.40"
tokio-util = { version = "0.7.8", features = ["codec"] }
